#	Copyright 2018, Google, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-prod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        version: prod
    spec:
      containers:
      - name: frontend
        image: docker.io/kumasan/kubernetesdemo:0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        env:
        - name: SERVICE_NAME
          value: "frontend-prod"
        - name: REQUEST_URL
          value: "http://middleware/"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: middleware-prod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: middleware
        version: prod
    spec:
      containers:
      - name: middleware
        image: docker.io/kumasan/kubernetesdemo:0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        env:
        - name: SERVICE_NAME
          value: "middleware-prod"
        - name: REQUEST_URL
          value: "http://backend/"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: middleware-canary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: middleware
        version: canary
    spec:
      containers:
      - name: middleware
        image: docker.io/kumasan/kubernetesdemo:0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        env:
        - name: SERVICE_NAME
          value: "middleware-canary"
        - name: REQUEST_URL
          value: "http://backend/"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-prod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
        version: prod
    spec:
      containers:
      - name: backend
        image: docker.io/kumasan/kubernetesdemo:0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        env:
        - name: SERVICE_NAME
          value: "backend-prod"
        - name: REQUEST_URL
          value: "https://openwhisk.ng.bluemix.net/api/v1/web/tenntenn_dev/default/helloGo.json?name=GCPUFukuoka"